### ISSUE TITLE
Platform detection is needed

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#2]
Right now the mod is blissfully ignorant when it comes to the cross-play situation.

We need to log whether the user is a Steam or Oculus user, and only show matches relevant to them in the browser.

**Comment by hpenney2** [comment]
From Zingabopp in the BSMG Discord:
> BS_Utils already has platform detection in [Gameplay.GetUserInfo](https://github.com/Kylemc1413/Beat-Saber-Utils/blob/master/Beat%20Saber%20Utils/Gameplay/UserInfo.cs#L104) (recommend using the task, it's more reliable)

**Comment by roydejong** [comment]
This is now implemented per 745e34d:
- Platform detection via BS_Utils, as described above (`GetUserInfo`)
- API server now supports "Platform" field ["unknown", "steam", "oculus"]
- When browsing for games, only games that are definitely on incompatible platforms are excluded

I'll keep this issue open, as I want to wait for this PR: https://github.com/Kylemc1413/Beat-Saber-Utils/pull/24

Also need to update dependencies to include BS_Utils.

**Comment by Zingabopp** [comment]
You don't have to wait for the PR, it just fixes it for people that have a mod that skips the HealthWarning screen.

**Comment by roydejong** [comment]
Fair point - worst case right now you see some incompatible games you can't connect to, in the unusual situation where you're skipping the Health Warning. When the new version of BS_Utils ships we'll update but it's not a big deal

603032af083e0af1297943dc1be9d96d44fc4e46 lists the dependency, so with that I'll close this
