### ISSUE TITLE
When joining a lobby and fails mods tab will show up on every menu tab

### ISSUE THREAD

**Issue by ItsCharaHere** [roydejong/BeatSaberServerBrowser#20]
To add onto this when this does occurr the in game hud will be on the ceiling of the in song scene

**Comment by roydejong** [comment]
Hey!

- Could you explain what you mean by "fails", what goes wrong exactly?
- Do you maybe have a screenshot of this issue you could share?

**Comment by ItsCharaHere** [comment]
What i mean by fails is when i try to join a lobby it fades to black (? cant remember exactly, will repo and get video when possible) then gives me a message saying that that lobby does not exist, when this happens any multiplayer lobby i attempt to join will say lobby does not exist, aswell after that if i go into solo and play a song, my combo and multiplier will be moved to the roof, along with the UI pillar things and my timer(?) from counters plus will be in the center of the lanes on the floor

**Comment by roydejong** [comment]
Hmm, it's a bit tricky to pinpoint because of all the mods doing different things.

The in-game counters and UI getting weird is *probably* related to MpEx, as it has settings that change your game HUD.

Your exact issue sounds rather strange though, haven't quite heard that one before, so a video would be very helpful to paint a picture. 👍

**Comment by ItsCharaHere** [comment]
alrighty, ill get back to this issue with a video and log when i can, it seems pretty common for me afaik

**Comment by ItsCharaHere** [comment]
Alrighty, here is a video of the bug occuring and a log of the incident 
Had to drop the file size really small to upload but you can see i try to join a lobby, it fails, then my solo hud breaks

[Beat Saber 2020.11.30 - 18.59.02.39.DVR_Trim_Trim_Trim.zip](https://github.com/roydejong/BeatSaberServerBrowser/files/5620060/Beat.Saber.2020.11.30.-.18.59.02.39.DVR_Trim_Trim_Trim.zip)
[_latest.log](https://github.com/roydejong/BeatSaberServerBrowser/files/5620066/_latest.log)

**Comment by ItsCharaHere** [comment]
Ive realized that this issue is not a problem with beat saber server browser but possibly MPEX, im going to forward this issue over to that repo
