### ISSUE TITLE
MultiplayerExtensions not detected

### ISSUE THREAD

**Issue by kevklam** [roydejong/BeatSaberServerBrowser#24]
Since installing multiplayer extensions 0.4.1, when I open server browser, it now says "multiplayer extensions not detected, hiding blablabla". I'm not really sure what's wrong, it doesn't show any errors in the log file, and I see MultiplayerExtension logs also that seem to indicate it's loading. Any ideas?

**Comment by roydejong** [comment]
I haven't been able to reproduce this myself, would you mind sharing your log?

**Comment by kevklam** [comment]
Sorry, it turns out there was some kind of issue with the discord presence mod that broke this. Removing that mod fixed it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roydejong** [comment]
Okay, thanks for the update. I'll leave this issue up though, I want to take a look to see where things are breaking
