### ISSUE TITLE
Release for 1.18.x / 1.19.x

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#42]
The server browser is functionally ready to release, and I'm satisfied things are stable for how multiplayer works since 1.16.3.

I'm waiting for BeatTogether and MultiplayerExtensions to be out of testing and publicly released first.

**Comment by Alan38** [comment]
BeatTogether and MultiplayerExtensions have been released 3h ago, I personally look forward to the release of the ServerBrowser and thank you again for the quality work you provide to us <3

**Comment by roydejong** [comment]
I've [published the release here](https://github.com/roydejong/BeatSaberServerBrowser/releases/tag/ServerBrowser-0.7.4-bs1.18.3-b43b8a4) for now for anyone looking for it.

I'll hold off on posting it on BSMG for a while though; BeatTogether is working through some server issues, and MpEx itself hasn't been posted there yet.

**Comment by roydejong** [comment]
I've posted the release up on BSMG; MpEx is up now and people are reporting it helps them avoid BeatTogether server issues so this seems like the right time to do so
