### ISSUE TITLE
Stability issues on 1.18

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#44]
Now that mods are live for 1.17 / 1.18, there seem to be some stability issues.

It's tricky to figure out in which mod or part the problem lies (ServerBrowser, MpEx/MqEx, BeatTogether?), but I just wanted to track things that I've noticed so far:

- [x] General: Games seem to drop off the server browser very quickly, even when they're still seemingly live - why?
- [x] General: Lobby stability issues - can't start new song after another one completes? (Start button is blocked)
- [x] Data: Player list often disappears on bssb.app, probably due to server resetting on host migrations?
- [ ] Host migrations: Sometimes Server Browser isn't aware local player is party leader and game drops off?

**Comment by roydejong** [comment]
Changes made so far:
 - bssb server will no longer reset player lists: https://github.com/roydejong/bssb.app/commit/855e1c56226f7bacbb968f7763a272c23b030f86

**Comment by Goldschlager23** [comment]
Hello Roydejong. I keep getting and my friend an error about no song selected when we both select the same song. The player who joined the session can ready up but the host cannot start the song as it keep saying no song selected.. We tried reversing the role and still the same.. What am i forgetting to do?

**Comment by roydejong** [comment]
> Hello Roydejong. I keep getting and my friend an error about no song selected when we both select the same song. The player who joined the session can ready up but the host cannot start the song as it keep saying no song selected.. We tried reversing the role and still the same.. What am i forgetting to do?

This sounds like an issue with BeatTogether/MultiplayerExtensions. I recommend asking in the #help channel on the [BeatTogether discord](https://discord.com/invite/gezGrFG4tz ).

Note the BeatTogether devs are still working on some stability issues, they are aware that lobbies can get "stuck" sometimes.

**Comment by Goldschlager23** [comment]
Thank you so much and i will.

**Comment by roydejong** [comment]
> Hello Roydejong. I keep getting and my friend an error about no song selected when we both select the same song. The player who joined the session can ready up but the host cannot start the song as it keep saying no song selected.. We tried reversing the role and still the same.. What am i forgetting to do?

Also, if you're seeing "no song selected", make sure you didn't accidentally select official servers. Official servers do not support custom songs, even with MultiplayerExtensions.

Ensure you have BeatTogether installed, and make sure "BeatTogether" is also the selected master server in the Online menu:
![image](https://user-images.githubusercontent.com/6772638/142293086-1effa9fa-bf87-4467-8867-e2add89312ad.png)

**Comment by roydejong** [comment]
Splitting remaining stuff off into their own issues, things are stable enough on this end
