### ISSUE TITLE
Browser: Filter full games / filter games in progress

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#5]
It would be nice to have some extra filter options:

- [ ] Filter out full servers
- [ ] Filter out games in progress
- [ ] Filter out modded games (MultiplayerExtensions)

I think it would be good to add these as toggle buttons in the keyboard modal, similar to how BeatSaverDownloader does this for filtering autogenerated songs.

This is low priority and becomes especially useful if the mod sees a lot of use, so we'll see how important this becomes down the line.

**Comment by hpenney2** [comment]
There should also be an option for filtering in or out modded servers (servers with custom songs enabled in MappingExtensions).

**Comment by roydejong** [comment]
Side note, #7 is now complete and automatically filters out modded games for vanilla players
