### ISSUE TITLE
Getting Multiplayer Extensions not loaded error

### ISSUE THREAD

**Issue by asebak** [roydejong/BeatSaberServerBrowser#51]
I took the latest dlls of both and getting this error? Any ideas?

**Comment by roydejong** [comment]
What version of Beat Saber are you using?

Please attach a Beat Saber log file as well so I can take a closer look (`latest.log`).

Note: If you're trying to use this mod with an early MultiplayerCore build, that's not yet supported. I'll make a proper release when they publicly release.

Thanks.

**Comment by asebak** [comment]
I figured out the issue my self with the logs, should have checked first.
