### ISSUE TITLE
BeatUpServer support / detection

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#68]
BeatUpServer is not properly recognized by the mod currently.

- [x] Server type is announced as "unknown"
- [x] Lobby status seems invalid?
- [x] Announce fails with HTTP 500 (Internal Server Error) during gameplay

**Comment by rcelyte** [comment]
What do you mean by " Lobby status seems invalid"?

**Comment by roydejong** [comment]
> What do you mean by "Lobby status seems invalid"?

I noticed a BeatUpServer lobby that had a status of "None", but I haven't actually been able to reproduce this so far.

I believe the client sets this status on disconnect, so it may have just been unlucky timing with the announce going out. This may just be something I have to patch on the API side.
