### ISSUE TITLE
'Create Server' UI doesn't account for elements from other mods

### ISSUE THREAD

**Issue by rcelyte** [roydejong/BeatSaberServerBrowser#71]
`ServerBrowser.UI.Forms.RefreshVerticalLayout()` overrides the height of the server creation form, misplacing the buttons if additional UI elements are present.
![menu](https://user-images.githubusercontent.com/25163630/173261632-852f1edb-e9e8-4219-b666-1d2e41107899.png)

**Comment by roydejong** [comment]
Thanks, do you have a mod I can test with?

**Comment by rcelyte** [comment]
Yes! [The latest version of BeatUpClient](https://github.com/rcelyte/BeatUpRcelyte/releases/tag/0.3.1)

**Comment by roydejong** [comment]
Got it to play nice with some effort. This mod will now do less layout fuckery and instead rely on `ContentFitter` to do its job:

![image](https://user-images.githubusercontent.com/6772638/178108826-91b1ce0c-fda1-4c0c-98c0-6d213f73dd73.png)
