### ISSUE TITLE
Puts me into spectator mode

### ISSUE THREAD

**Issue by Jaitie018** [roydejong/BeatSaberServerBrowser#8]
Sometimes when I join a match in a modded lobby it puts me into spectator mode and sometimes it says "I don't own the song"

**Comment by roydejong** [comment]
Hey, this is most likely related to MultiplayerExtensions. That mod is still in active development so things can break.

Your issue sounds like it might happen if custom a song fails to download from BeatSaver on time.

**Comment by Galacton** [comment]
> Sometimes when I join a match in a modded lobby it puts me into spectator mode and sometimes it says "I don't own the song"

The best way to make sure this doesn't happen is to click on the song that will be played under suggested songs on the right. That makes sure that the song gets downloaded and imported and it will show up in the selected song menu once it's done downloading. I discovered this over the past couple of days of testing.

**Comment by Jaitie018** [comment]
more likely the song won't show up under suggested songs. and sometimes I can play the song but the song info will not show up
