### ISSUE TITLE
Feature: Native UI

### ISSUE THREAD

**Issue by roydejong** [roydejong/BeatSaberServerBrowser#9]
The game has a native UI for a server browser. It's marked "dev" so unsure if they're working on this, or whether it's for developer use only, but perhaps it's worth exploring using this rather than a custom BSML UI.

![image](https://user-images.githubusercontent.com/6772638/98268966-70e77980-1f8d-11eb-92f1-3f68271db060.png)

**Comment by Galacton** [comment]
This would be really cool to see implemented in-game even if it doesn't get added to the mod, along with cross-play.

**Comment by roydejong** [comment]
I've been playing around with this, mostly for fun

![image](https://user-images.githubusercontent.com/6772638/98447239-82fb2080-2123-11eb-9674-9901889a7c59.png)

**Comment by roydejong** [comment]
Some more WIP progress

![image](https://user-images.githubusercontent.com/6772638/98461397-0d876280-21ac-11eb-8796-c628f07c1934.png)

**Comment by roydejong** [comment]
Checklist to finish the implementation:

- [ ] **Filter / search**: modal keyboard and, ideally, integrate filter options from #5
- [ ] **Song information**: display current level info / art
- [ ] **Hover and selection effects**: highlight background when hovering / selecting item
- [ ] **Test with many results**: testing / performance tweaks when dealing with many results
- [ ] **Tweak refresh button**: top-right can't be clicked?

**Comment by roydejong** [comment]
A preview of the native browser will ship with v0.2.0 but it won't be enabled by default.

If you want to play around with it, set `UseNativeBrowserPreview` to `true` in your settings (`UserData/ServerBrowser.json`).

![image](https://user-images.githubusercontent.com/6772638/99151619-cfeb7380-269c-11eb-8ea4-8a9e6ea3f261.png)

This project was fun but frankly there are too many problems to actually ship this, it's probably best to concentrate efforts towards making the custom UI better, so I'm closing this issue up.
